"""empty message

Revision ID: 982563463f0
Revises: 36b93d81ad60
Create Date: 2015-02-25 13:15:36.255997

"""

# revision identifiers, used by Alembic.
revision = '982563463f0'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Dominik', sa.String(), nullable=False),
    sa.Column('Machura', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Machura', 'loguser', ['Machura'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_Machura', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
